
#define BASS_VST_VERSION_STR		"2.4.1"
#define BASS_VST_VERSION_HEX		0x02040100L
#define BASS_VST_VERSION_MAJOR		2
#define BASS_VST_VERSION_MINOR		4
#define BASS_VST_VERSION_REV_MAJOR	1
#define BASS_VST_VERSION_REV_MINOR	0
